ci: Upgrade to manylinux 2.28
koordinates/kart pull request #1027
Opened 2024-12-11 19:22 UTC by craigds

## Description

manylinux2014 is ancient enough that a lot of github actions are starting to not run on it any more; the amount of effort required to deal with this image seems to be rapidly escalating.

This PR upgrades to manylinux_2_28 images.

I think this means Kart is now expected to run on OSes with glibc 2.28 or newer:

>    Debian 10+
>    Ubuntu 18.10+
>    Fedora 29+
>    CentOS/RHEL 8+

In other words Kart on Linux now requires an OS newer than 5-6 years old.

## Related links:

https://github.com/pypa/manylinux?tab=readme-ov-file#manylinux_2_28-almalinux-8-based

## Checklist:

- [ ] Have you reviewed your own change?
- [ ] Have you included test(s)?
- [ ] Have you updated the [changelog](https://github.com/koordinates/kart/blob/master/CHANGELOG.md)?

2024-12-11 21:27 UTC, rcoup requested changes
LGTM except the libffi thing.

2024-12-11 21:27 UTC, rcoup commented on vcpkg-vendor/fix_vendor_libs.py
> +        "/usr/lib/libffi.dylib",
we _build_ libffi via vcpkg, we definitely shouldn't be using the system libffi

https://github.com/koordinates/kart/blob/ea74d9ea0cf86cce3e2adf75ee298e157fcf57af/vcpkg-vendor/vcpkg.json#L73

2024-12-15 22:30 UTC, olsen232 approved these changes

2024-12-15 22:41 UTC, merged

2024-12-16 11:21 UTC, rcoup commented
(I presume `/usr/local/` here was meant to be `/usr/lib/`?)

> Allow deps from /usr/local/ to be found in vendor
>
> Previous logic was that deps with prefix /usr/local/ are "system" deps and either whitelisted or disallowed, but are not searched for in vcpkg-vendor.
> Removed this concept - now if any dep is not whitelisted as a system dep, we search for it in vcpkg-vendor, regardless of its prefix.

Doesn't this mean we'll unilaterally update a library to depend on the vcpkg version instead of the system one?

eg:
1. `/usr/lib/libfoo` is a random system library
2. we build `libfoo` via vcpkg
3. we build a python wheel which is meant to link to our `libfoo`. But it doesn't find it, and links to the system one instead.
4. we find the issue during fix-vendor-libs: previously we would error, but now we just update the library dependencies to point to the vcpkg one?

I mean, in practise it's probably fine? Since ABIs are versioned (`libfoo.99.dylib`), and the vcpkg one will be newer than the system one in basically all cases...